### ISSUE TITLE
Support peertube

### ISSUE THREAD

**Issue by headap** [Tubefeeder/Tubefeeder#18]
It would be great to consolidate youtube and peertube subscriptions into one feed.

**Comment by Schmiddiii** [comment]
I have already thought about supporting other video platforms (mainly lbry).
It would be possible, but before I can do that I will have to rewrite major parts of the app since it is not maintainable in the current state.

I currently do not have time for a major rewrite but I will probably have at the end of the month.

In summary I will implement such a feature, but please do not expect it any time soon.
