### ISSUE TITLE
[idea] pre-download items in the Watch Later list

### ISSUE THREAD

**Issue by JulienPalard** [Tubefeeder/Tubefeeder#30]
Idea is when I click the "Watch later" button to add a video in the watch later list, Tubefeeder could start youtube-dl to prefetch the video, so it's already here "later" when I want to watch it.

**Comment by Schmiddiii** [comment]
A nice idea, but I believe that this should either be a setting or a per-video option as most people probably do not want to download the video on mobile data. Another idea would be making the downloading independent of the watch-later list, e.g. a new button, and clicking on the video after downloading plays the downloaded video instead of fetching the video. A GUI indicator for downloaded videos would probably also be nice.

**Comment by Schmiddiii** [comment]
I have now implemented basic download-functionality to Tubefeeder. I have decided against doing it in the watch-later-list, instead every video has a "download"-button hidden behind a expandable area next to the "watch-later"-button.

Note that this will download the highest quality video, which can take a long time. There is no real indicator of the download-percentage, the "currently-playing"-indicator is used. 
To change the download-setting, change the `DOWNLOADER` environmental variable, for example to `yt-dlp -f 'bestvideo[height<=480]+bestaudio/best[height<=480]' --output '$HOME/Downloads/%(title)s-%(id)s.%(ext)s'` for the best 480p video. 
Do not forget to set the output directory to `Downloads` as the Flatpak only has access to this directory.
Also notice the use of `yt-dlp` instead of `youtube-dl` as this is built into the Flatpak.

Please test out the new functionality in Flathub-beta.
