### ISSUE TITLE
Support import of subscriptions from Newpipe

### ISSUE THREAD

**Issue by mickenordin** [Tubefeeder/Tubefeeder#44]
Hello fellow youtube enjoyers :)

It would be fantastic if it could be possible to add support for import of subacriptions from newpipe. Here is an example of such an export from Newpipe:

https://code.smolnet.org/micke/cast/src/branch/main/src/yt_subs.json

This is what I do in my (only half finished) youtube app written in Python: https://code.smolnet.org/micke/cast/src/branch/main/src/Utils/__init__.py#L216

It would make me so happy if you would implement this, because then I could retire my app, as yours seems so much nicer :)

**Comment by Schmiddiii** [comment]
I believe there is already a way (but I have not tested this for a while, and the storage of subscriptions has changed since then).

See: https://www.tubefeeder.de/wiki/migrating.html

As the storage of subscriptions has changed, make sure to clean up `.local/share/tubefeeder` before converting.

Please inform me if this still works or if any problems arise during conversion.

**Comment by Schmiddiii** [comment]
I have tried it out myself and it still seems to be working. Here are the needed commands (where the current directory is the repository and `yt_subs.json` are your exported subscriptions) (assuming that `~/.local/share/tubefeeder/` does not yet contain a `subscriptions.csv`):

- `./tools/newpipe_to_tubefeeder.json yt_subs.json > subscriptions.db`
- `mv subscriptions.db ~/.local/share/tubefeeder/`
- Start Tubefeeder

This currently does not work in the `gtk4v2`-branch, I will fix this before publishing.
